### ISSUE TITLE
AY-7462_Colorspace error in Nuke 13.2

### ISSUE THREAD

**Issue by vivimage** [ynput/ayon-nuke#50]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
A concise description of what you're experiencing.

```
Traceback (most recent call last):
  File "/studio/tools/nuke/nuke13.2/plugins/nuke_internal/callbacks.py", line 72, in onCreate
    _doCallbacks(onCreates)
  File "/studio/tools/nuke/nuke13.2/plugins/nuke_internal/callbacks.py", line 46, in _doCallbacks
    f[0](*f[1],**f[2])
  File "/home/ivanov/Documents/VSCodeProjects/ayon-docker/addons/nuke/ayon-nuke/client/ayon_nuke/api/lib.py", line 2037, in set_context_settings
    self.set_colorspace()
  File "/home/ivanov/Documents/VSCodeProjects/ayon-docker/addons/nuke/ayon-nuke/client/ayon_nuke/api/lib.py", line 1873, in set_colorspace
    self.set_viewers_colorspace(nuke_colorspace)
  File "/home/ivanov/Documents/VSCodeProjects/ayon-docker/addons/nuke/ayon-nuke/client/ayon_nuke/api/lib.py", line 1446, in set_viewers_colorspace
    if viewer_process not in v["viewerProcess"].value():
TypeError: 'in <string>' requires string as left operand, not NoneType
```

## Expected Behavior
A concise description of what you expected to happen.

It should work as expected

### Steps To Reproduce:

from ayon_nuke.api.colorspace import get_formatted_display_and_view
view_profile = {"view": "{context};sRGB","display": "{project_code};ACES"}
formatting_data = {"context": "01sh010","project_code": "proj01"}
display_and_view = get_formatted_display_and_view(view_profile, formatting_data)
print(display_and_view)

Run this code inside nuke 13.2 

### Additional context:

https://github.com/ynput/ayon-nuke/blob/2c525a8d48359ad400bcdba026d72ccffc7ddc93/client/ayon_nuke/api/colorspace.py#L186

If in this line 
```
create_viewer_profile_string(
                    view.strip(), display.strip(), path_like=False
                )
```

change to path_like=True

it works without error

### Relevant log output:

```shell

```

**Comment by jakubjezek001** [comment]
Thank you for reporting the issue. We might be looking into it at some point but for now no client was reporting the issue. I would like to encourage you  to create PullRequest with the fix if you are having it solved.

**Comment by ralphmeijerambassadors** [comment]
Did you ever managed solve this issues? We are running into the same issue. I'm suspecting it has something to do with how the color transforms are configured in the settings but I wasn't successful to find the issue so far.

**Comment by BigRoy** [comment]
@ralphmeijerambassadors The issue description describes in "Additional Context" how @vivimage ended up fixing it. Any chance you can confirm the relevant change?

I also saw this PR the other day https://github.com/ynput/ayon-nuke/pull/60 which also influences how colorspaces from Nuke are parsed and collected and may be relevant to issues in this area too.

However, aside of the community reports here I haven't heard much others about issues in this area so more knowledge on how to reproduce it exactly is more than welcome. In this case @vivimage seems to describe it's Nuke 13.2 specific?

**Comment by ralphmeijerambassadors** [comment]
I digged a bit further and it was what I expected. I configured the viewer with the wrong transform. It's a bit trial and error to find the right names but I managed to fix it. Thanks!

**Comment by BigRoy** [comment]
> I digged a bit further and it was what I expected. I configured the viewer with the wrong transform. It's a bit trial and error to find the right names but I managed to fix it. Thanks!

For completeness sake (and me not knowing anything about Nuke or the Nuke integration). Could you clarify _where_ you tweaked that and how did you find it?

Is it something that should be captured differently in the code and could e.g. be auto-fixed or logged with more clarity? If so, details would be greatly appreciated.

**Comment by ralphmeijerambassadors** [comment]
I filled in the correct transform in the Nuke settings:

![Image](https://github.com/user-attachments/assets/e1f7cc94-bc81-499b-9aa6-4f9827f25a0c)

I guess having a dropdown based on your ocio would solve the issues for getting the correct names and formatting. I think I've seen another post related to this where a developer explained that might be a harder than it seems since the ocio needs to be parsed with the correct names. I don't think it's impossible though.

**Comment by BigRoy** [comment]
Thanks!

> I guess having a dropdown based on your ocio would solve the issues for getting the correct names and formatting. I think I've seen another post related to this where a developer explained that might be a harder than it seems since the ocio needs to be parsed with the correct names. I don't think it's impossible though.

The trickiest bit here is that the OCIO file may live on your network share or on your machine - but _not_ on the AYON server (which may be in a very different location or network) and hence it cannot parse such a file to display the info needed. Unless the OCIO woud always be server from the server itself, or we 'attach' it manually in some other way but that is also not fool proof unfortunately.

**However** if _this_ is what causes that issue I think we should definitely work towards generating a much better error log, etc.

**Comment by jakubjezek001** [comment]
I was just testing the issue at latest ayon-nuke `0.3.1+dev` and all seems to be working as expected

**Comment by MustafaJafar** [comment]
I was able to replicate this issue in the current dev state of Nuke `0.3.1+dev` addon where this function call can return `None`. 

https://github.com/ynput/ayon-nuke/blob/1833ced9fc0069f54ef1964f818cb99d3f24a0bf/client/ayon_nuke/api/lib.py#L1465-L1467

It returns `None` on my side if I've wrong values in settings.
Maybe we can add some hint for users about that. I wrote this little piece of code to test the results. 

Also, I wonder if we want to check `if viewer_process not in v["viewerProcess"].values()` instead of `if viewer_process not in v["viewerProcess"].value()`. 
and also I wonder can avoid setting the knob if the value is `None`

 
```python
import nuke 

import ayon_api
from ayon_core.pipeline.context_tools import get_current_project_name
from ayon_core.settings import get_project_settings
from ayon_nuke.api.lib import WorkfileSettings
from ayon_nuke.api.colorspace import get_formatted_display_and_view


project_name = get_current_project_name()

project_entity = ayon_api.get_project(project_name, fields={"name", "code", "taskTypes"})
project_settings = get_project_settings(project_name)

imageio_settings = project_settings["nuke"]["imageio"]

workfile_settings = WorkfileSettings()
viewer_process = get_formatted_display_and_view(
    imageio_settings["viewer"], workfile_settings.formatting_data, nuke.root()
)

nodes = nuke.allNodes(filter="Viewer")
for node in nodes:
    if viewer_process not in node["viewerProcess"].values():
        print(f"{viewer_process} not found in the available viewer list.")
```

**Comment by MustafaJafar** [comment]
I was able to replicate this issue in the current dev state of Nuke `0.3.1+dev` addon where this function call can return `None`. 

https://github.com/ynput/ayon-nuke/blob/1833ced9fc0069f54ef1964f818cb99d3f24a0bf/client/ayon_nuke/api/lib.py#L1465-L1467

It returns `None` on my side if I've wrong values in settings.
Maybe we can add some hint for users about that. I wrote this little piece of code to test the results. 

```python
import nuke 

import ayon_api
from ayon_core.pipeline.context_tools import get_current_project_name
from ayon_core.settings import get_project_settings
from ayon_nuke.api.lib import WorkfileSettings
from ayon_nuke.api.colorspace import get_formatted_display_and_view


project_name = get_current_project_name()

project_entity = ayon_api.get_project(project_name, fields={"name", "code", "taskTypes"})
project_settings = get_project_settings(project_name)

imageio_settings = project_settings["nuke"]["imageio"]

workfile_settings = WorkfileSettings()
viewer_process = get_formatted_display_and_view(
    imageio_settings["viewer"], workfile_settings.formatting_data, nuke.root()
)

nodes = nuke.allNodes(filter="Viewer")
for node in nodes:
    if viewer_process not in node["viewerProcess"].values():
        print(f"{viewer_process} not found in the available viewer list.")
```
----
Regarding

https://github.com/ynput/ayon-nuke/blob/1833ced9fc0069f54ef1964f818cb99d3f24a0bf/client/ayon_nuke/api/lib.py#L1465-L1467

I wonder if we want to check `if viewer_process not in v["viewerProcess"].values()` instead of `if viewer_process not in v["viewerProcess"].value()`. 

Regarding

https://github.com/ynput/ayon-nuke/blob/1833ced9fc0069f54ef1964f818cb99d3f24a0bf/client/ayon_nuke/api/lib.py#L1473-L1474

I wonder can avoid setting the knob if the value is `None`

**Comment by jakubjezek001** [comment]
related issue #76

**Comment by jakubjezek001** [comment]
resolved via https://github.com/ynput/ayon-nuke/pull/79
